name       : progress
version    : 0.13.1
release    : 1
source     :
    - https://github.com/Xfennec/progress/archive/v0.13.1.tar.gz : 064c95e8b93893dbf4b4b8152290cbb3b0c005eda0cae500353561048c9939a5
license    : GPL-3.0
component  : system.utils
summary    : Coreutils Progress Viewer
description: |
    progress is a tiny, dirty, C command that looks for coreutils basic commands (cp, mv, dd, tar,
    gzip/gunzip, cat, etc.) currently running on your system and displays the percentage of copied
    data. It can also show estimated time and throughput, and provides a "top-like" mode
    (monitoring).
setup      : |
    sed -e "s:ncurses:ncursesw:g" -i Makefile
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
