name       : progress
version    : '0.16'
release    : 4
source     :
    - https://github.com/Xfennec/progress/archive/refs/tags/v0.16.tar.gz : 59944ee35f8ae6d62ed4f9b643eee2ae6d03825da288d9779dc43de41164c834
license    : GPL-3.0-or-later
component  : system.utils
summary    : Coreutils Progress Viewer
description: |
    progress is a tiny, dirty, C command that looks for coreutils basic commands (cp, mv, dd, tar,
    gzip/gunzip, cat, etc.) currently running on your system and displays the percentage of copied
    data. It can also show estimated time and throughput, and provides a "top-like" mode
    (monitoring).
setup      : |
    sed -e "s:ncurses:ncursesw:g" -i Makefile
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
